python3 -m run --ginc configs/mipnerf360/tnt.gin --scene_name tat_intermediate_M60
python3 -m run --ginc configs/mipnerf360/tnt.gin --scene_name tat_intermediate_Playground
python3 -m run --ginc configs/mipnerf360/tnt.gin --scene_name tat_intermediate_Train
python3 -m run --ginc configs/mipnerf360/tnt.gin --scene_name tat_training_Truck
python3 -m run --ginc configs/mipnerf360/lf.gin --scene_name africa
python3 -m run --ginc configs/mipnerf360/lf.gin --scene_name basket
python3 -m run --ginc configs/mipnerf360/lf.gin --scene_name ship
python3 -m run --ginc configs/mipnerf360/lf.gin --scene_name statue
python3 -m run --ginc configs/mipnerf360/lf.gin --scene_name torch
python3 -m run --ginc configs/mipnerf360/360_v2.gin --scene_name bicycle
python3 -m run --ginc configs/mipnerf360/360_v2.gin --scene_name bonsai
python3 -m run --ginc configs/mipnerf360/360_v2.gin --scene_name counter
python3 -m run --ginc configs/mipnerf360/360_v2.gin --scene_name garden
python3 -m run --ginc configs/mipnerf360/360_v2.gin --scene_name kitchen
python3 -m run --ginc configs/mipnerf360/360_v2.gin --scene_name room
python3 -m run --ginc configs/mipnerf360/360_v2.gin --scene_name stump
python3 -m run --ginc configs/mipnerf360/llff.gin --scene_name fern
python3 -m run --ginc configs/mipnerf360/llff.gin --scene_name flower
python3 -m run --ginc configs/mipnerf360/llff.gin --scene_name fortress
python3 -m run --ginc configs/mipnerf360/llff.gin --scene_name horns
python3 -m run --ginc configs/mipnerf360/llff.gin --scene_name leaves
python3 -m run --ginc configs/mipnerf360/llff.gin --scene_name orchids
python3 -m run --ginc configs/mipnerf360/llff.gin --scene_name room
python3 -m run --ginc configs/mipnerf360/llff.gin --scene_name trex