python3 -m run --ginc configs/plenoxel/blender.gin --scene_name chair
python3 -m run --ginc configs/plenoxel/blender.gin --scene_name drums
python3 -m run --ginc configs/plenoxel/blender.gin --scene_name ficus
python3 -m run --ginc configs/plenoxel/blender.gin --scene_name hotdog
python3 -m run --ginc configs/plenoxel/blender.gin --scene_name lego
python3 -m run --ginc configs/plenoxel/blender.gin --scene_name materials
python3 -m run --ginc configs/plenoxel/blender.gin --scene_name mic
python3 -m run --ginc configs/plenoxel/blender.gin --scene_name ship
python3 -m run --ginc configs/plenoxel/llff.gin --scene_name fern
python3 -m run --ginc configs/plenoxel/llff.gin --scene_name flower
python3 -m run --ginc configs/plenoxel/llff.gin --scene_name fortress
python3 -m run --ginc configs/plenoxel/llff.gin --scene_name horns
python3 -m run --ginc configs/plenoxel/llff.gin --scene_name orchids
python3 -m run --ginc configs/plenoxel/llff.gin --scene_name leaves
python3 -m run --ginc configs/plenoxel/llff.gin --scene_name room
python3 -m run --ginc configs/plenoxel/llff.gin --scene_name trex
python3 -m run --ginc configs/plenoxel/tnt.gin --scene_name tat_intermediate_M60
python3 -m run --ginc configs/plenoxel/tnt.gin --scene_name tat_intermediate_Playground
python3 -m run --ginc configs/plenoxel/tnt.gin --scene_name tat_intermediate_Train
python3 -m run --ginc configs/plenoxel/tnt.gin --scene_name tat_training_Truck
python3 -m run --ginc configs/plenoxel/lf.gin --scene_name africa
python3 -m run --ginc configs/plenoxel/lf.gin --scene_name basket
python3 -m run --ginc configs/plenoxel/lf.gin --scene_name ship
python3 -m run --ginc configs/plenoxel/lf.gin --scene_name statue
python3 -m run --ginc configs/plenoxel/lf.gin --scene_name torch
python3 -m run --ginc configs/plenoxel/blender_ms.gin --scene_name chair
python3 -m run --ginc configs/plenoxel/blender_ms.gin --scene_name drums
python3 -m run --ginc configs/plenoxel/blender_ms.gin --scene_name ficus
python3 -m run --ginc configs/plenoxel/blender_ms.gin --scene_name hotdog
python3 -m run --ginc configs/plenoxel/blender_ms.gin --scene_name lego
python3 -m run --ginc configs/plenoxel/blender_ms.gin --scene_name materials
python3 -m run --ginc configs/plenoxel/blender_ms.gin --scene_name mic
python3 -m run --ginc configs/plenoxel/blender_ms.gin --scene_name ship
python3 -m run --ginc configs/plenoxel/360_v2.gin --scene_name bicycle
python3 -m run --ginc configs/plenoxel/360_v2.gin --scene_name bonsai
python3 -m run --ginc configs/plenoxel/360_v2.gin --scene_name counter
python3 -m run --ginc configs/plenoxel/360_v2.gin --scene_name garden
python3 -m run --ginc configs/plenoxel/360_v2.gin --scene_name kitchen
python3 -m run --ginc configs/plenoxel/360_v2.gin --scene_name room
python3 -m run --ginc configs/plenoxel/360_v2.gin --scene_name stump
python3 -m run --ginc configs/plenoxel/shiny_blender.gin --scene_name ball
python3 -m run --ginc configs/plenoxel/shiny_blender.gin --scene_name car
python3 -m run --ginc configs/plenoxel/shiny_blender.gin --scene_name coffee
python3 -m run --ginc configs/plenoxel/shiny_blender.gin --scene_name helmet
python3 -m run --ginc configs/plenoxel/shiny_blender.gin --scene_name teapot
python3 -m run --ginc configs/plenoxel/shiny_blender.gin --scene_name toaster