python3 -m run --ginc configs/refnerf/blender.gin --scene_name chair
python3 -m run --ginc configs/refnerf/blender.gin --scene_name drums
python3 -m run --ginc configs/refnerf/blender.gin --scene_name ficus
python3 -m run --ginc configs/refnerf/blender.gin --scene_name hotdog
python3 -m run --ginc configs/refnerf/blender.gin --scene_name lego
python3 -m run --ginc configs/refnerf/blender.gin --scene_name materials
python3 -m run --ginc configs/refnerf/blender.gin --scene_name mic
python3 -m run --ginc configs/refnerf/blender.gin --scene_name ship
python3 -m run --ginc configs/refnerf/shiny_blender.gin --scene_name ball
python3 -m run --ginc configs/refnerf/shiny_blender.gin --scene_name car
python3 -m run --ginc configs/refnerf/shiny_blender.gin --scene_name coffee
python3 -m run --ginc configs/refnerf/shiny_blender.gin --scene_name helmet
python3 -m run --ginc configs/refnerf/shiny_blender.gin --scene_name teapot
python3 -m run --ginc configs/refnerf/shiny_blender.gin --scene_name toaster