python3 -m run --ginc configs/mipnerf/blender.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name lego
python3 -m run --ginc configs/mipnerf/llff.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room
python3 -m run --ginc configs/mipnerf/tnt.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name tat_intermediate_Playground
python3 -m run --ginc configs/mipnerf/lf.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name ship
python3 -m run --ginc configs/mipnerf/blender_ms.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name lego
python3 -m run --ginc configs/mipnerf/360_v2.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room
python3 -m run --ginc configs/mipnerf360/tnt.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name tat_intermediate_Playground
python3 -m run --ginc configs/mipnerf360/lf.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name ship
python3 -m run --ginc configs/mipnerf360/360_v2.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room
python3 -m run --ginc configs/mipnerf360/llff.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room
python3 -m run --ginc configs/nerf/blender.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name lego
python3 -m run --ginc configs/nerf/llff.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room
python3 -m run --ginc configs/nerf/tnt.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name tat_intermediate_Playground
python3 -m run --ginc configs/nerf/lf.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name ship
python3 -m run --ginc configs/nerf/blender_ms.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name lego
python3 -m run --ginc configs/nerf/360_v2.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room
python3 -m run --ginc configs/nerfpp/tnt.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name tat_intermediate_Playground
python3 -m run --ginc configs/nerfpp/lf.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name ship
python3 -m run --ginc configs/nerfpp/360_v2.gin --ginb LitData.epoch_size=2000 --ginb run.max_steps=2000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room
python3 -m run --ginc configs/dvgo/blender.gin --ginb LitData.epoch_size=10000 --ginb run.max_steps=10000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name lego 
python3 -m run --ginc configs/dvgo/llff.gin --ginb LitData.epoch_size=10000 --ginb run.max_steps=10000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room
python3 -m run --ginc configs/dvgo/tnt.gin --ginb LitData.epoch_size=10000 --ginb run.max_steps=10000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name tat_intermediate_Playground
python3 -m run --ginc configs/dvgo/lf.gin --ginb LitData.epoch_size=10000 --ginb run.max_steps=10000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name ship
python3 -m run --ginc configs/dvgo/360_v2.gin --ginb LitData.epoch_size=10000 --ginb run.max_steps=10000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room
python3 -m run --ginc configs/plenoxel/blender.gin --ginb LitData.epoch_size=100000 --ginb run.max_steps=100000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name lego
python3 -m run --ginc configs/plenoxel/llff.gin --ginb LitData.epoch_size=100000 --ginb run.max_steps=100000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room
python3 -m run --ginc configs/plenoxel/blender_ms.gin --ginb LitData.epoch_size=100000 --ginb run.max_steps=100000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name lego
python3 -m run --ginc configs/plenoxel/tnt.gin --ginb LitData.epoch_size=100000 --ginb run.max_steps=100000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name tat_intermediate_Playground
python3 -m run --ginc configs/plenoxel/lf.gin --ginb LitData.epoch_size=100000 --ginb run.max_steps=100000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name ship
python3 -m run --ginc configs/plenoxel/360_v2.gin --ginb LitData.epoch_size=100000 --ginb run.max_steps=100000 --ginb run.postfix="'test'" --ginb LitData.batch_size=512 --scene_name room